package co.edu.usb.clusterbp;
// Generated 11/03/2017 12:29:01 AM by Hibernate Tools 5.1.0.Final



/**
 * Estructural generated by hbm2java
 */
public class Estructural  implements java.io.Serializable {


     private Long estructuralCodigo;
     private Pn pn;
     private String id;
     private String fromId;
     private String toId;
     private String fromActividad;
     private String toActividad;

    public Estructural() {
    }

	
    public Estructural(Long estructuralCodigo, Pn pn, String id, String fromActividad, String toActividad) {
        this.estructuralCodigo = estructuralCodigo;
        this.pn = pn;
        this.id = id;
        this.fromActividad = fromActividad;
        this.toActividad = toActividad;
    }
    public Estructural(Long estructuralCodigo, Pn pn, String id, String fromId, String toId, String fromActividad, String toActividad) {
       this.estructuralCodigo = estructuralCodigo;
       this.pn = pn;
       this.id = id;
       this.fromId = fromId;
       this.toId = toId;
       this.fromActividad = fromActividad;
       this.toActividad = toActividad;
    }
   
    public Long getEstructuralCodigo() {
        return this.estructuralCodigo;
    }
    
    public void setEstructuralCodigo(Long estructuralCodigo) {
        this.estructuralCodigo = estructuralCodigo;
    }
    public Pn getPn() {
        return this.pn;
    }
    
    public void setPn(Pn pn) {
        this.pn = pn;
    }
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getFromId() {
        return this.fromId;
    }
    
    public void setFromId(String fromId) {
        this.fromId = fromId;
    }
    public String getToId() {
        return this.toId;
    }
    
    public void setToId(String toId) {
        this.toId = toId;
    }
    public String getFromActividad() {
        return this.fromActividad;
    }
    
    public void setFromActividad(String fromActividad) {
        this.fromActividad = fromActividad;
    }
    public String getToActividad() {
        return this.toActividad;
    }
    
    public void setToActividad(String toActividad) {
        this.toActividad = toActividad;
    }




}


