package co.edu.usb.clusterbp;
// Generated 17/01/2017 09:07:37 PM by Hibernate Tools 4.3.1.Final


import java.util.Date;

/**
 * GrupoUsuario generated by hbm2java
 */
public class GrupoUsuario  implements java.io.Serializable {


     private Long grupoUsuarioCodigo;
     private Grupo grupo;
     private Usuario usuario;
     private Long usuCreador;
     private Date fechaCreacion;
     private Long usuModificador;
     private Date fechaModificacion;

    public GrupoUsuario() {
    }

	
    public GrupoUsuario(Long grupoUsuarioCodigo, Grupo grupo, Usuario usuario, Long usuCreador, Date fechaCreacion) {
        this.grupoUsuarioCodigo = grupoUsuarioCodigo;
        this.grupo = grupo;
        this.usuario = usuario;
        this.usuCreador = usuCreador;
        this.fechaCreacion = fechaCreacion;
    }
    public GrupoUsuario(Long grupoUsuarioCodigo, Grupo grupo, Usuario usuario, Long usuCreador, Date fechaCreacion, Long usuModificador, Date fechaModificacion) {
       this.grupoUsuarioCodigo = grupoUsuarioCodigo;
       this.grupo = grupo;
       this.usuario = usuario;
       this.usuCreador = usuCreador;
       this.fechaCreacion = fechaCreacion;
       this.usuModificador = usuModificador;
       this.fechaModificacion = fechaModificacion;
    }
   
    public Long getGrupoUsuarioCodigo() {
        return this.grupoUsuarioCodigo;
    }
    
    public void setGrupoUsuarioCodigo(Long grupoUsuarioCodigo) {
        this.grupoUsuarioCodigo = grupoUsuarioCodigo;
    }
    public Grupo getGrupo() {
        return this.grupo;
    }
    
    public void setGrupo(Grupo grupo) {
        this.grupo = grupo;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Long getUsuCreador() {
        return this.usuCreador;
    }
    
    public void setUsuCreador(Long usuCreador) {
        this.usuCreador = usuCreador;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Long getUsuModificador() {
        return this.usuModificador;
    }
    
    public void setUsuModificador(Long usuModificador) {
        this.usuModificador = usuModificador;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }




}


