package co.edu.usb.clusterbp;
// Generated 17/01/2017 09:07:37 PM by Hibernate Tools 4.3.1.Final


import java.util.Date;

/**
 * GrupoRepositorio generated by hbm2java
 */
public class GrupoRepositorio  implements java.io.Serializable {


     private Long grupoRepositorioCodigo;
     private Grupo grupo;
     private Repositorio repositorio;
     private Long usuCreador;
     private Date fechaCreacion;
     private Long usuModificador;
     private Date fechaModificacion;

    public GrupoRepositorio() {
    }

	
    public GrupoRepositorio(Long grupoRepositorioCodigo, Grupo grupo, Repositorio repositorio, Long usuCreador, Date fechaCreacion) {
        this.grupoRepositorioCodigo = grupoRepositorioCodigo;
        this.grupo = grupo;
        this.repositorio = repositorio;
        this.usuCreador = usuCreador;
        this.fechaCreacion = fechaCreacion;
    }
    public GrupoRepositorio(Long grupoRepositorioCodigo, Grupo grupo, Repositorio repositorio, Long usuCreador, Date fechaCreacion, Long usuModificador, Date fechaModificacion) {
       this.grupoRepositorioCodigo = grupoRepositorioCodigo;
       this.grupo = grupo;
       this.repositorio = repositorio;
       this.usuCreador = usuCreador;
       this.fechaCreacion = fechaCreacion;
       this.usuModificador = usuModificador;
       this.fechaModificacion = fechaModificacion;
    }
   
    public Long getGrupoRepositorioCodigo() {
        return this.grupoRepositorioCodigo;
    }
    
    public void setGrupoRepositorioCodigo(Long grupoRepositorioCodigo) {
        this.grupoRepositorioCodigo = grupoRepositorioCodigo;
    }
    public Grupo getGrupo() {
        return this.grupo;
    }
    
    public void setGrupo(Grupo grupo) {
        this.grupo = grupo;
    }
    public Repositorio getRepositorio() {
        return this.repositorio;
    }
    
    public void setRepositorio(Repositorio repositorio) {
        this.repositorio = repositorio;
    }
    public Long getUsuCreador() {
        return this.usuCreador;
    }
    
    public void setUsuCreador(Long usuCreador) {
        this.usuCreador = usuCreador;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Long getUsuModificador() {
        return this.usuModificador;
    }
    
    public void setUsuModificador(Long usuModificador) {
        this.usuModificador = usuModificador;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }




}


