package co.edu.usb.clusterbp;
// Generated 17/01/2017 09:07:37 PM by Hibernate Tools 4.3.1.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Grupo generated by hbm2java
 */
public class Grupo  implements java.io.Serializable {


     private Long grupoCodigo;
     private String nombre;
     private Long usuCreador;
     private Date fechaCreacion;
     private Long usuModificador;
     private Date fechaModificacion;
     private String activo;
     private Set<GrupoRepositorio> grupoRepositorios = new HashSet<GrupoRepositorio>(0);
     private Set<GrupoUsuario> grupoUsuarios = new HashSet<GrupoUsuario>(0);

    public Grupo() {
    }

	
    public Grupo(Long grupoCodigo, String nombre, Long usuCreador, Date fechaCreacion, String activo) {
        this.grupoCodigo = grupoCodigo;
        this.nombre = nombre;
        this.usuCreador = usuCreador;
        this.fechaCreacion = fechaCreacion;
        this.activo = activo;
    }
    public Grupo(Long grupoCodigo, String nombre, Long usuCreador, Date fechaCreacion, Long usuModificador, Date fechaModificacion, String activo, Set<GrupoRepositorio> grupoRepositorios, Set<GrupoUsuario> grupoUsuarios) {
       this.grupoCodigo = grupoCodigo;
       this.nombre = nombre;
       this.usuCreador = usuCreador;
       this.fechaCreacion = fechaCreacion;
       this.usuModificador = usuModificador;
       this.fechaModificacion = fechaModificacion;
       this.activo = activo;
       this.grupoRepositorios = grupoRepositorios;
       this.grupoUsuarios = grupoUsuarios;
    }
   
    public Long getGrupoCodigo() {
        return this.grupoCodigo;
    }
    
    public void setGrupoCodigo(Long grupoCodigo) {
        this.grupoCodigo = grupoCodigo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Long getUsuCreador() {
        return this.usuCreador;
    }
    
    public void setUsuCreador(Long usuCreador) {
        this.usuCreador = usuCreador;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Long getUsuModificador() {
        return this.usuModificador;
    }
    
    public void setUsuModificador(Long usuModificador) {
        this.usuModificador = usuModificador;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public String getActivo() {
        return this.activo;
    }
    
    public void setActivo(String activo) {
        this.activo = activo;
    }
    public Set<GrupoRepositorio> getGrupoRepositorios() {
        return this.grupoRepositorios;
    }
    
    public void setGrupoRepositorios(Set<GrupoRepositorio> grupoRepositorios) {
        this.grupoRepositorios = grupoRepositorios;
    }
    public Set<GrupoUsuario> getGrupoUsuarios() {
        return this.grupoUsuarios;
    }
    
    public void setGrupoUsuarios(Set<GrupoUsuario> grupoUsuarios) {
        this.grupoUsuarios = grupoUsuarios;
    }




}


