package co.edu.usb.clusterbp;
// Generated 17/01/2017 09:07:37 PM by Hibernate Tools 4.3.1.Final


import java.util.Date;

/**
 * Historial generated by hbm2java
 */
public class Historial  implements java.io.Serializable {


     private Long historialCodigo;
     private Pn pn;
     private String titulo;
     private String descripcion;
     private Long usuCreador;
     private Date fechaCreacion;
     private Long usuModificador;
     private Date fechaModificacion;
     private String activo;
     private byte[] archivo;

    public Historial() {
    }

	
    public Historial(Long historialCodigo, Pn pn, String titulo, Long usuCreador, Date fechaCreacion, String activo, byte[] archivo) {
        this.historialCodigo = historialCodigo;
        this.pn = pn;
        this.titulo = titulo;
        this.usuCreador = usuCreador;
        this.fechaCreacion = fechaCreacion;
        this.activo = activo;
        this.archivo = archivo;
    }
    public Historial(Long historialCodigo, Pn pn, String titulo, String descripcion, Long usuCreador, Date fechaCreacion, Long usuModificador, Date fechaModificacion, String activo, byte[] archivo) {
       this.historialCodigo = historialCodigo;
       this.pn = pn;
       this.titulo = titulo;
       this.descripcion = descripcion;
       this.usuCreador = usuCreador;
       this.fechaCreacion = fechaCreacion;
       this.usuModificador = usuModificador;
       this.fechaModificacion = fechaModificacion;
       this.activo = activo;
       this.archivo = archivo;
    }
   
    public Long getHistorialCodigo() {
        return this.historialCodigo;
    }
    
    public void setHistorialCodigo(Long historialCodigo) {
        this.historialCodigo = historialCodigo;
    }
    public Pn getPn() {
        return this.pn;
    }
    
    public void setPn(Pn pn) {
        this.pn = pn;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Long getUsuCreador() {
        return this.usuCreador;
    }
    
    public void setUsuCreador(Long usuCreador) {
        this.usuCreador = usuCreador;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Long getUsuModificador() {
        return this.usuModificador;
    }
    
    public void setUsuModificador(Long usuModificador) {
        this.usuModificador = usuModificador;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public String getActivo() {
        return this.activo;
    }
    
    public void setActivo(String activo) {
        this.activo = activo;
    }
    public byte[] getArchivo() {
        return this.archivo;
    }
    
    public void setArchivo(byte[] archivo) {
        this.archivo = archivo;
    }




}


