package co.edu.usb.clusterbp;
// Generated 17/01/2017 09:07:37 PM by Hibernate Tools 4.3.1.Final


import java.util.Date;

/**
 * LogBusqueda generated by hbm2java
 */
public class LogBusqueda  implements java.io.Serializable {


     private Long logBusquedaCodigo;
     private Repositorio repositorio;
     private String descLog;
     private Long usuCreador;
     private Date fechaCreacion;
     private Long usuModificador;
     private Date fechaModificacion;
     private String activo;

    public LogBusqueda() {
    }

	
    public LogBusqueda(Long logBusquedaCodigo, Repositorio repositorio, String descLog, Long usuCreador, Date fechaCreacion, String activo) {
        this.logBusquedaCodigo = logBusquedaCodigo;
        this.repositorio = repositorio;
        this.descLog = descLog;
        this.usuCreador = usuCreador;
        this.fechaCreacion = fechaCreacion;
        this.activo = activo;
    }
    public LogBusqueda(Long logBusquedaCodigo, Repositorio repositorio, String descLog, Long usuCreador, Date fechaCreacion, Long usuModificador, Date fechaModificacion, String activo) {
       this.logBusquedaCodigo = logBusquedaCodigo;
       this.repositorio = repositorio;
       this.descLog = descLog;
       this.usuCreador = usuCreador;
       this.fechaCreacion = fechaCreacion;
       this.usuModificador = usuModificador;
       this.fechaModificacion = fechaModificacion;
       this.activo = activo;
    }
   
    public Long getLogBusquedaCodigo() {
        return this.logBusquedaCodigo;
    }
    
    public void setLogBusquedaCodigo(Long logBusquedaCodigo) {
        this.logBusquedaCodigo = logBusquedaCodigo;
    }
    public Repositorio getRepositorio() {
        return this.repositorio;
    }
    
    public void setRepositorio(Repositorio repositorio) {
        this.repositorio = repositorio;
    }
    public String getDescLog() {
        return this.descLog;
    }
    
    public void setDescLog(String descLog) {
        this.descLog = descLog;
    }
    public Long getUsuCreador() {
        return this.usuCreador;
    }
    
    public void setUsuCreador(Long usuCreador) {
        this.usuCreador = usuCreador;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Long getUsuModificador() {
        return this.usuModificador;
    }
    
    public void setUsuModificador(Long usuModificador) {
        this.usuModificador = usuModificador;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public String getActivo() {
        return this.activo;
    }
    
    public void setActivo(String activo) {
        this.activo = activo;
    }




}


