package co.edu.usb.clusterbp;
// Generated 17/01/2017 09:07:37 PM by Hibernate Tools 4.3.1.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ModeloBusqueda generated by hbm2java
 */
public class ModeloBusqueda  implements java.io.Serializable {


     private Long modeloBusquedaCodigo;
     private String nombre;
     private Long usuCreador;
     private Date fechaCreacion;
     private Long usuModificador;
     private Date fechaModificacion;
     private String activo;
     private Set<PluginModeloBusqueda> pluginModeloBusquedas = new HashSet<PluginModeloBusqueda>(0);

    public ModeloBusqueda() {
    }

	
    public ModeloBusqueda(Long modeloBusquedaCodigo, String nombre, Long usuCreador, Date fechaCreacion, String activo) {
        this.modeloBusquedaCodigo = modeloBusquedaCodigo;
        this.nombre = nombre;
        this.usuCreador = usuCreador;
        this.fechaCreacion = fechaCreacion;
        this.activo = activo;
    }
    public ModeloBusqueda(Long modeloBusquedaCodigo, String nombre, Long usuCreador, Date fechaCreacion, Long usuModificador, Date fechaModificacion, String activo, Set<PluginModeloBusqueda> pluginModeloBusquedas) {
       this.modeloBusquedaCodigo = modeloBusquedaCodigo;
       this.nombre = nombre;
       this.usuCreador = usuCreador;
       this.fechaCreacion = fechaCreacion;
       this.usuModificador = usuModificador;
       this.fechaModificacion = fechaModificacion;
       this.activo = activo;
       this.pluginModeloBusquedas = pluginModeloBusquedas;
    }
   
    public Long getModeloBusquedaCodigo() {
        return this.modeloBusquedaCodigo;
    }
    
    public void setModeloBusquedaCodigo(Long modeloBusquedaCodigo) {
        this.modeloBusquedaCodigo = modeloBusquedaCodigo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Long getUsuCreador() {
        return this.usuCreador;
    }
    
    public void setUsuCreador(Long usuCreador) {
        this.usuCreador = usuCreador;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Long getUsuModificador() {
        return this.usuModificador;
    }
    
    public void setUsuModificador(Long usuModificador) {
        this.usuModificador = usuModificador;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public String getActivo() {
        return this.activo;
    }
    
    public void setActivo(String activo) {
        this.activo = activo;
    }
    public Set<PluginModeloBusqueda> getPluginModeloBusquedas() {
        return this.pluginModeloBusquedas;
    }
    
    public void setPluginModeloBusquedas(Set<PluginModeloBusqueda> pluginModeloBusquedas) {
        this.pluginModeloBusquedas = pluginModeloBusquedas;
    }




}


