package co.edu.usb.clusterbp;
// Generated 17/01/2017 09:07:37 PM by Hibernate Tools 4.3.1.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Plugin generated by hbm2java
 */
public class Plugin  implements java.io.Serializable {


     private Long pluginCodigo;
     private String titulo;
     private String descripcion;
     private Long usuCreador;
     private Date fechaCreacion;
     private Long usuModificador;
     private Date fechaModificacion;
     private String activo;
     private Set<PluginModeloBusqueda> pluginModeloBusquedas = new HashSet<PluginModeloBusqueda>(0);
     private Set<RepositorioPlugin> repositorioPlugins = new HashSet<RepositorioPlugin>(0);

    public Plugin() {
    }

	
    public Plugin(Long pluginCodigo, String titulo, Long usuCreador, Date fechaCreacion, String activo) {
        this.pluginCodigo = pluginCodigo;
        this.titulo = titulo;
        this.usuCreador = usuCreador;
        this.fechaCreacion = fechaCreacion;
        this.activo = activo;
    }
    public Plugin(Long pluginCodigo, String titulo, String descripcion, Long usuCreador, Date fechaCreacion, Long usuModificador, Date fechaModificacion, String activo, Set<PluginModeloBusqueda> pluginModeloBusquedas, Set<RepositorioPlugin> repositorioPlugins) {
       this.pluginCodigo = pluginCodigo;
       this.titulo = titulo;
       this.descripcion = descripcion;
       this.usuCreador = usuCreador;
       this.fechaCreacion = fechaCreacion;
       this.usuModificador = usuModificador;
       this.fechaModificacion = fechaModificacion;
       this.activo = activo;
       this.pluginModeloBusquedas = pluginModeloBusquedas;
       this.repositorioPlugins = repositorioPlugins;
    }
   
    public Long getPluginCodigo() {
        return this.pluginCodigo;
    }
    
    public void setPluginCodigo(Long pluginCodigo) {
        this.pluginCodigo = pluginCodigo;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Long getUsuCreador() {
        return this.usuCreador;
    }
    
    public void setUsuCreador(Long usuCreador) {
        this.usuCreador = usuCreador;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Long getUsuModificador() {
        return this.usuModificador;
    }
    
    public void setUsuModificador(Long usuModificador) {
        this.usuModificador = usuModificador;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public String getActivo() {
        return this.activo;
    }
    
    public void setActivo(String activo) {
        this.activo = activo;
    }
    public Set<PluginModeloBusqueda> getPluginModeloBusquedas() {
        return this.pluginModeloBusquedas;
    }
    
    public void setPluginModeloBusquedas(Set<PluginModeloBusqueda> pluginModeloBusquedas) {
        this.pluginModeloBusquedas = pluginModeloBusquedas;
    }
    public Set<RepositorioPlugin> getRepositorioPlugins() {
        return this.repositorioPlugins;
    }
    
    public void setRepositorioPlugins(Set<RepositorioPlugin> repositorioPlugins) {
        this.repositorioPlugins = repositorioPlugins;
    }




}


