package co.edu.usb.clusterbp;
// Generated 17/01/2017 09:07:37 PM by Hibernate Tools 4.3.1.Final


import java.util.Date;

/**
 * PluginModeloBusqueda generated by hbm2java
 */
public class PluginModeloBusqueda  implements java.io.Serializable {


     private Long pluginModeloBusquedaCodigo;
     private ModeloBusqueda modeloBusqueda;
     private Plugin plugin;
     private Long usuCreador;
     private Date fechaCreacion;
     private Long usuModificador;
     private Date fechaModificacion;
     private String activo;

    public PluginModeloBusqueda() {
    }

	
    public PluginModeloBusqueda(Long pluginModeloBusquedaCodigo, ModeloBusqueda modeloBusqueda, Plugin plugin, Long usuCreador, Date fechaCreacion, String activo) {
        this.pluginModeloBusquedaCodigo = pluginModeloBusquedaCodigo;
        this.modeloBusqueda = modeloBusqueda;
        this.plugin = plugin;
        this.usuCreador = usuCreador;
        this.fechaCreacion = fechaCreacion;
        this.activo = activo;
    }
    public PluginModeloBusqueda(Long pluginModeloBusquedaCodigo, ModeloBusqueda modeloBusqueda, Plugin plugin, Long usuCreador, Date fechaCreacion, Long usuModificador, Date fechaModificacion, String activo) {
       this.pluginModeloBusquedaCodigo = pluginModeloBusquedaCodigo;
       this.modeloBusqueda = modeloBusqueda;
       this.plugin = plugin;
       this.usuCreador = usuCreador;
       this.fechaCreacion = fechaCreacion;
       this.usuModificador = usuModificador;
       this.fechaModificacion = fechaModificacion;
       this.activo = activo;
    }
   
    public Long getPluginModeloBusquedaCodigo() {
        return this.pluginModeloBusquedaCodigo;
    }
    
    public void setPluginModeloBusquedaCodigo(Long pluginModeloBusquedaCodigo) {
        this.pluginModeloBusquedaCodigo = pluginModeloBusquedaCodigo;
    }
    public ModeloBusqueda getModeloBusqueda() {
        return this.modeloBusqueda;
    }
    
    public void setModeloBusqueda(ModeloBusqueda modeloBusqueda) {
        this.modeloBusqueda = modeloBusqueda;
    }
    public Plugin getPlugin() {
        return this.plugin;
    }
    
    public void setPlugin(Plugin plugin) {
        this.plugin = plugin;
    }
    public Long getUsuCreador() {
        return this.usuCreador;
    }
    
    public void setUsuCreador(Long usuCreador) {
        this.usuCreador = usuCreador;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Long getUsuModificador() {
        return this.usuModificador;
    }
    
    public void setUsuModificador(Long usuModificador) {
        this.usuModificador = usuModificador;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public String getActivo() {
        return this.activo;
    }
    
    public void setActivo(String activo) {
        this.activo = activo;
    }




}


