package co.edu.usb.clusterbp;
// Generated 17/01/2017 09:07:37 PM by Hibernate Tools 4.3.1.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pn generated by hbm2java
 */
public class Pn  implements java.io.Serializable {


     private Long pnCodigo;
     private TipoArchivoPn tipoArchivoPn;
     private String titulo;
     private String descripcion;
     private Long usuCreador;
     private Date fechaCreacion;
     private Long usuModificador;
     private Date fechaModificacion;
     private String activo;
     private byte[] archivo;
     private Set<Historial> historials = new HashSet<Historial>(0);
     private Set<RepositorioPn> repositorioPns = new HashSet<RepositorioPn>(0);

    public Pn() {
    }

	
    public Pn(Long pnCodigo, TipoArchivoPn tipoArchivoPn, String titulo, Long usuCreador, Date fechaCreacion, String activo, byte[] archivo) {
        this.pnCodigo = pnCodigo;
        this.tipoArchivoPn = tipoArchivoPn;
        this.titulo = titulo;
        this.usuCreador = usuCreador;
        this.fechaCreacion = fechaCreacion;
        this.activo = activo;
        this.archivo = archivo;
    }
    public Pn(Long pnCodigo, TipoArchivoPn tipoArchivoPn, String titulo, String descripcion, Long usuCreador, Date fechaCreacion, Long usuModificador, Date fechaModificacion, String activo, byte[] archivo, Set<Historial> historials, Set<RepositorioPn> repositorioPns) {
       this.pnCodigo = pnCodigo;
       this.tipoArchivoPn = tipoArchivoPn;
       this.titulo = titulo;
       this.descripcion = descripcion;
       this.usuCreador = usuCreador;
       this.fechaCreacion = fechaCreacion;
       this.usuModificador = usuModificador;
       this.fechaModificacion = fechaModificacion;
       this.activo = activo;
       this.archivo = archivo;
       this.historials = historials;
       this.repositorioPns = repositorioPns;
    }
   
    public Long getPnCodigo() {
        return this.pnCodigo;
    }
    
    public void setPnCodigo(Long pnCodigo) {
        this.pnCodigo = pnCodigo;
    }
    public TipoArchivoPn getTipoArchivoPn() {
        return this.tipoArchivoPn;
    }
    
    public void setTipoArchivoPn(TipoArchivoPn tipoArchivoPn) {
        this.tipoArchivoPn = tipoArchivoPn;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Long getUsuCreador() {
        return this.usuCreador;
    }
    
    public void setUsuCreador(Long usuCreador) {
        this.usuCreador = usuCreador;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Long getUsuModificador() {
        return this.usuModificador;
    }
    
    public void setUsuModificador(Long usuModificador) {
        this.usuModificador = usuModificador;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public String getActivo() {
        return this.activo;
    }
    
    public void setActivo(String activo) {
        this.activo = activo;
    }
    public byte[] getArchivo() {
        return this.archivo;
    }
    
    public void setArchivo(byte[] archivo) {
        this.archivo = archivo;
    }
    public Set<Historial> getHistorials() {
        return this.historials;
    }
    
    public void setHistorials(Set<Historial> historials) {
        this.historials = historials;
    }
    public Set<RepositorioPn> getRepositorioPns() {
        return this.repositorioPns;
    }
    
    public void setRepositorioPns(Set<RepositorioPn> repositorioPns) {
        this.repositorioPns = repositorioPns;
    }




}


