package co.edu.usb.clusterbp;
// Generated 16/03/2017 09:42:06 PM by Hibernate Tools 5.1.0.Final



/**
 * PnTxt generated by hbm2java
 */
public class PnTxt  implements java.io.Serializable {


     private Long pnTxtCodigo;
     private Pn pn;
     private String texto;
     private String clustering;

    public PnTxt() {
    }

	
    public PnTxt(Long pnTxtCodigo, Pn pn) {
        this.pnTxtCodigo = pnTxtCodigo;
        this.pn = pn;
    }
    public PnTxt(Long pnTxtCodigo, Pn pn, String texto, String clustering) {
       this.pnTxtCodigo = pnTxtCodigo;
       this.pn = pn;
       this.texto = texto;
       this.clustering=clustering;
    }
   
    public Long getPnTxtCodigo() {
        return this.pnTxtCodigo;
    }
    
    public void setPnTxtCodigo(Long pnTxtCodigo) {
        this.pnTxtCodigo = pnTxtCodigo;
    }
    public Pn getPn() {
        return this.pn;
    }
    
    public void setPn(Pn pn) {
        this.pn = pn;
    }
    public String getTexto() {
        return this.texto;
    }
    
    public void setTexto(String texto) {
        this.texto = texto;
    }

	public String getClustering() {
		return clustering;
	}

	public void setClustering(String clustering) {
		this.clustering = clustering;
	}

}


