package co.edu.usb.clusterbp;
// Generated 17/01/2017 09:07:37 PM by Hibernate Tools 4.3.1.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Repositorio generated by hbm2java
 */
public class Repositorio  implements java.io.Serializable {


     private Long repositorioCodigo;
     private String nombre;
     private String descripcion;
     private Long usuCreador;
     private Date fechaCreacion;
     private Long usuModificador;
     private Date fechaModificacion;
     private String activo;
     private Set<VersionRep> versionReps = new HashSet<VersionRep>(0);
     private Set<RepositorioPn> repositorioPns = new HashSet<RepositorioPn>(0);
     private Set<GrupoRepositorio> grupoRepositorios = new HashSet<GrupoRepositorio>(0);
     private Set<LogBusqueda> logBusquedas = new HashSet<LogBusqueda>(0);
     private Set<RepositorioPlugin> repositorioPlugins = new HashSet<RepositorioPlugin>(0);

    public Repositorio() {
    }

	
    public Repositorio(Long repositorioCodigo, String nombre, String descripcion, Long usuCreador, Date fechaCreacion, String activo) {
        this.repositorioCodigo = repositorioCodigo;
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.usuCreador = usuCreador;
        this.fechaCreacion = fechaCreacion;
        this.activo = activo;
    }
    public Repositorio(Long repositorioCodigo, String nombre, String descripcion, Long usuCreador, Date fechaCreacion, Long usuModificador, Date fechaModificacion, String activo, Set<VersionRep> versionReps, Set<RepositorioPn> repositorioPns, Set<GrupoRepositorio> grupoRepositorios, Set<LogBusqueda> logBusquedas, Set<RepositorioPlugin> repositorioPlugins) {
       this.repositorioCodigo = repositorioCodigo;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.usuCreador = usuCreador;
       this.fechaCreacion = fechaCreacion;
       this.usuModificador = usuModificador;
       this.fechaModificacion = fechaModificacion;
       this.activo = activo;
       this.versionReps = versionReps;
       this.repositorioPns = repositorioPns;
       this.grupoRepositorios = grupoRepositorios;
       this.logBusquedas = logBusquedas;
       this.repositorioPlugins = repositorioPlugins;
    }
   
    public Long getRepositorioCodigo() {
        return this.repositorioCodigo;
    }
    
    public void setRepositorioCodigo(Long repositorioCodigo) {
        this.repositorioCodigo = repositorioCodigo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Long getUsuCreador() {
        return this.usuCreador;
    }
    
    public void setUsuCreador(Long usuCreador) {
        this.usuCreador = usuCreador;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Long getUsuModificador() {
        return this.usuModificador;
    }
    
    public void setUsuModificador(Long usuModificador) {
        this.usuModificador = usuModificador;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public String getActivo() {
        return this.activo;
    }
    
    public void setActivo(String activo) {
        this.activo = activo;
    }
    public Set<VersionRep> getVersionReps() {
        return this.versionReps;
    }
    
    public void setVersionReps(Set<VersionRep> versionReps) {
        this.versionReps = versionReps;
    }
    public Set<RepositorioPn> getRepositorioPns() {
        return this.repositorioPns;
    }
    
    public void setRepositorioPns(Set<RepositorioPn> repositorioPns) {
        this.repositorioPns = repositorioPns;
    }
    public Set<GrupoRepositorio> getGrupoRepositorios() {
        return this.grupoRepositorios;
    }
    
    public void setGrupoRepositorios(Set<GrupoRepositorio> grupoRepositorios) {
        this.grupoRepositorios = grupoRepositorios;
    }
    public Set<LogBusqueda> getLogBusquedas() {
        return this.logBusquedas;
    }
    
    public void setLogBusquedas(Set<LogBusqueda> logBusquedas) {
        this.logBusquedas = logBusquedas;
    }
    public Set<RepositorioPlugin> getRepositorioPlugins() {
        return this.repositorioPlugins;
    }
    
    public void setRepositorioPlugins(Set<RepositorioPlugin> repositorioPlugins) {
        this.repositorioPlugins = repositorioPlugins;
    }




}


