package co.edu.usb.clusterbp;
// Generated 17/01/2017 09:07:37 PM by Hibernate Tools 4.3.1.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Rol generated by hbm2java
 */
public class Rol  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long rolCodigo;
     private String nombre;
     private Long usuCreador;
     private Date fechaCreacion;
     private Long usuarioModificador;
     private Date fechaModificacion;
     private String activo;
     private Set<UsuarioRol> usuarioRols = new HashSet<UsuarioRol>(0);

    public Rol() {
    }

	
    public Rol(Long rolCodigo, String nombre, Long usuCreador, Date fechaCreacion, String activo) {
        this.rolCodigo = rolCodigo;
        this.nombre = nombre;
        this.usuCreador = usuCreador;
        this.fechaCreacion = fechaCreacion;
        this.activo = activo;
    }
    public Rol(Long rolCodigo, String nombre, Long usuCreador, Date fechaCreacion, Long usuarioModificador, Date fechaModificacion, String activo, Set<UsuarioRol> usuarioRols) {
       this.rolCodigo = rolCodigo;
       this.nombre = nombre;
       this.usuCreador = usuCreador;
       this.fechaCreacion = fechaCreacion;
       this.usuarioModificador = usuarioModificador;
       this.fechaModificacion = fechaModificacion;
       this.activo = activo;
       this.usuarioRols = usuarioRols;
    }
   
    public Long getRolCodigo() {
        return this.rolCodigo;
    }
    
    public void setRolCodigo(Long rolCodigo) {
        this.rolCodigo = rolCodigo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Long getUsuCreador() {
        return this.usuCreador;
    }
    
    public void setUsuCreador(Long usuCreador) {
        this.usuCreador = usuCreador;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Long getUsuarioModificador() {
        return this.usuarioModificador;
    }
    
    public void setUsuarioModificador(Long usuarioModificador) {
        this.usuarioModificador = usuarioModificador;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public String getActivo() {
        return this.activo;
    }
    
    public void setActivo(String activo) {
        this.activo = activo;
    }
    public Set<UsuarioRol> getUsuarioRols() {
        return this.usuarioRols;
    }
    
    public void setUsuarioRols(Set<UsuarioRol> usuarioRols) {
        this.usuarioRols = usuarioRols;
    }




}


