package co.edu.usb.clusterbp;
// Generated 11/03/2017 12:29:01 AM by Hibernate Tools 5.1.0.Final



/**
 * Textual generated by hbm2java
 */
public class Textual  implements java.io.Serializable {


     private Long textualCodigo;
     private Pn pn;
     private String id;
     private String nombre;
     private String descripcion;
     private String actividad;

    public Textual() {
    }

	
    public Textual(Long textualCodigo, Pn pn, String id, String actividad) {
        this.textualCodigo = textualCodigo;
        this.pn = pn;
        this.id = id;
        this.actividad = actividad;
    }
    public Textual(Long textualCodigo, Pn pn, String id, String nombre, String descripcion, String actividad) {
       this.textualCodigo = textualCodigo;
       this.pn = pn;
       this.id = id;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.actividad = actividad;
    }
   
    public Long getTextualCodigo() {
        return this.textualCodigo;
    }
    
    public void setTextualCodigo(Long textualCodigo) {
        this.textualCodigo = textualCodigo;
    }
    public Pn getPn() {
        return this.pn;
    }
    
    public void setPn(Pn pn) {
        this.pn = pn;
    }
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getActividad() {
        return this.actividad;
    }
    
    public void setActividad(String actividad) {
        this.actividad = actividad;
    }




}


