package co.edu.usb.clusterbp;
// Generated 17/01/2017 09:07:37 PM by Hibernate Tools 4.3.1.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TipoArchivoPn generated by hbm2java
 */
public class TipoArchivoPn  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long tipoArchivoPnCodigo;
     private String nombre;
     private Long usuCreador;
     private Date fechaCreacion;
     private Long usuModificador;
     private Date fechaModificacion;
     private String activo;
     private Set<Pn> pns = new HashSet<Pn>(0);

    public TipoArchivoPn() {
    }

	
    public TipoArchivoPn(Long tipoArchivoPnCodigo, String nombre, Long usuCreador, Date fechaCreacion, String activo) {
        this.tipoArchivoPnCodigo = tipoArchivoPnCodigo;
        this.nombre = nombre;
        this.usuCreador = usuCreador;
        this.fechaCreacion = fechaCreacion;
        this.activo = activo;
    }
    public TipoArchivoPn(Long tipoArchivoPnCodigo, String nombre, Long usuCreador, Date fechaCreacion, Long usuModificador, Date fechaModificacion, String activo, Set<Pn> pns) {
       this.tipoArchivoPnCodigo = tipoArchivoPnCodigo;
       this.nombre = nombre;
       this.usuCreador = usuCreador;
       this.fechaCreacion = fechaCreacion;
       this.usuModificador = usuModificador;
       this.fechaModificacion = fechaModificacion;
       this.activo = activo;
       this.pns = pns;
    }
   
    public Long getTipoArchivoPnCodigo() {
        return this.tipoArchivoPnCodigo;
    }
    
    public void setTipoArchivoPnCodigo(Long tipoArchivoPnCodigo) {
        this.tipoArchivoPnCodigo = tipoArchivoPnCodigo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Long getUsuCreador() {
        return this.usuCreador;
    }
    
    public void setUsuCreador(Long usuCreador) {
        this.usuCreador = usuCreador;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Long getUsuModificador() {
        return this.usuModificador;
    }
    
    public void setUsuModificador(Long usuModificador) {
        this.usuModificador = usuModificador;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public String getActivo() {
        return this.activo;
    }
    
    public void setActivo(String activo) {
        this.activo = activo;
    }
    public Set<Pn> getPns() {
        return this.pns;
    }
    
    public void setPns(Set<Pn> pns) {
        this.pns = pns;
    }




}


