package co.edu.usb.clusterbp;
// Generated 11/03/2017 12:29:01 AM by Hibernate Tools 5.1.0.Final


import java.util.Date;

/**
 * TipoActividad generated by hbm2java
 */
public class TipoActividad  implements java.io.Serializable {


     private Long tipoActividadCodigo;
     private String nombre;
     private Long usuCreador;
     private Date fechaCreacion;
     private Long usuModificador;
     private Date fechaModificacion;
     private String activo;
     private byte[] imagen;

    public TipoActividad() {
    }

	
    public TipoActividad(Long tipoActividadCodigo, String nombre, Date fechaCreacion, String activo) {
        this.tipoActividadCodigo = tipoActividadCodigo;
        this.nombre = nombre;
        this.fechaCreacion = fechaCreacion;
        this.activo = activo;
    }
    public TipoActividad(Long tipoActividadCodigo, String nombre, Long usuCreador, Date fechaCreacion, Long usuModificador, Date fechaModificacion, String activo, byte[] imagen) {
       this.tipoActividadCodigo = tipoActividadCodigo;
       this.nombre = nombre;
       this.usuCreador = usuCreador;
       this.fechaCreacion = fechaCreacion;
       this.usuModificador = usuModificador;
       this.fechaModificacion = fechaModificacion;
       this.activo = activo;
       this.imagen = imagen;
    }
   
    public Long getTipoActividadCodigo() {
        return this.tipoActividadCodigo;
    }
    
    public void setTipoActividadCodigo(Long tipoActividadCodigo) {
        this.tipoActividadCodigo = tipoActividadCodigo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Long getUsuCreador() {
        return this.usuCreador;
    }
    
    public void setUsuCreador(Long usuCreador) {
        this.usuCreador = usuCreador;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Long getUsuModificador() {
        return this.usuModificador;
    }
    
    public void setUsuModificador(Long usuModificador) {
        this.usuModificador = usuModificador;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public String getActivo() {
        return this.activo;
    }
    
    public void setActivo(String activo) {
        this.activo = activo;
    }
    public byte[] getImagen() {
        return this.imagen;
    }
    
    public void setImagen(byte[] imagen) {
        this.imagen = imagen;
    }




}


