package co.edu.usb.clusterbp;
// Generated 11/03/2017 12:29:01 AM by Hibernate Tools 5.1.0.Final


import java.util.Date;

/**
 * TipoActividad generated by hbm2java
 */
public class TipoActividad  implements java.io.Serializable {


     private Long tipoActividadCodigo;
     private String nombre;
    

    public TipoActividad() {
    }

	
    public TipoActividad(Long tipoActividadCodigo, String nombre) {
        this.tipoActividadCodigo = tipoActividadCodigo;
        this.nombre = nombre;  
    }
    
    public TipoActividad(String nombre) {
       this.nombre = nombre;
    }
   
    public Long getTipoActividadCodigo() {
        return this.tipoActividadCodigo;
    }
    
    public void setTipoActividadCodigo(Long tipoActividadCodigo) {
        this.tipoActividadCodigo = tipoActividadCodigo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
}


