package co.edu.usb.clusterbp;
// Generated 17/01/2017 09:07:37 PM by Hibernate Tools 4.3.1.Final


import java.util.Date;

/**
 * UsuarioRol generated by hbm2java
 */
public class UsuarioRol  implements java.io.Serializable {


     private Long usuarioRolCodigo;
     private Rol rol;
     private Usuario usuario;
     private Long usuCreador;
     private Date fechaCreacion;
     private Long usuarioModificador;
     private Date fechaModificacion;

    public UsuarioRol() {
    }

	
    public UsuarioRol(Long usuarioRolCodigo, Rol rol, Usuario usuario, Long usuCreador, Date fechaCreacion) {
        this.usuarioRolCodigo = usuarioRolCodigo;
        this.rol = rol;
        this.usuario = usuario;
        this.usuCreador = usuCreador;
        this.fechaCreacion = fechaCreacion;
    }
    public UsuarioRol(Long usuarioRolCodigo, Rol rol, Usuario usuario, Long usuCreador, Date fechaCreacion, Long usuarioModificador, Date fechaModificacion) {
       this.usuarioRolCodigo = usuarioRolCodigo;
       this.rol = rol;
       this.usuario = usuario;
       this.usuCreador = usuCreador;
       this.fechaCreacion = fechaCreacion;
       this.usuarioModificador = usuarioModificador;
       this.fechaModificacion = fechaModificacion;
    }
   
    public Long getUsuarioRolCodigo() {
        return this.usuarioRolCodigo;
    }
    
    public void setUsuarioRolCodigo(Long usuarioRolCodigo) {
        this.usuarioRolCodigo = usuarioRolCodigo;
    }
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Long getUsuCreador() {
        return this.usuCreador;
    }
    
    public void setUsuCreador(Long usuCreador) {
        this.usuCreador = usuCreador;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Long getUsuarioModificador() {
        return this.usuarioModificador;
    }
    
    public void setUsuarioModificador(Long usuarioModificador) {
        this.usuarioModificador = usuarioModificador;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }




}


