package co.edu.usb.clusterbp;
// Generated 17/01/2017 09:07:37 PM by Hibernate Tools 4.3.1.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Long usuarioCodigo;
     private String correo;
     private String clave;
     private String nombre;
     private Long usuCreador;
     private Date fechaCreacion;
     private Long usuaModificador;
     private Date fechaModificacion;
     private String activo;
     private Set<UsuarioRol> usuarioRols = new HashSet<UsuarioRol>(0);

    public Usuario() {
    }

	
    public Usuario(Long usuarioCodigo, String correo, String clave, String nombre, Long usuCreador, Date fechaCreacion, String activo) {
        this.usuarioCodigo = usuarioCodigo;
        this.correo = correo;
        this.clave = clave;
        this.nombre = nombre;
        this.usuCreador = usuCreador;
        this.fechaCreacion = fechaCreacion;
        this.activo = activo;
    }
    public Usuario(Long usuarioCodigo, String correo, String clave, String nombre, Long usuCreador, Date fechaCreacion, Long usuaModificador, Date fechaModificacion, String activo, Set<UsuarioRol> usuarioRols) {
       this.usuarioCodigo = usuarioCodigo;
       this.correo = correo;
       this.clave = clave;
       this.nombre = nombre;
       this.usuCreador = usuCreador;
       this.fechaCreacion = fechaCreacion;
       this.usuaModificador = usuaModificador;
       this.fechaModificacion = fechaModificacion;
       this.activo = activo;
       this.usuarioRols = usuarioRols;
    }
   
    public Long getUsuarioCodigo() {
        return this.usuarioCodigo;
    }
    
    public void setUsuarioCodigo(Long usuarioCodigo) {
        this.usuarioCodigo = usuarioCodigo;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Long getUsuCreador() {
        return this.usuCreador;
    }
    
    public void setUsuCreador(Long usuCreador) {
        this.usuCreador = usuCreador;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Long getUsuaModificador() {
        return this.usuaModificador;
    }
    
    public void setUsuaModificador(Long usuaModificador) {
        this.usuaModificador = usuaModificador;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public String getActivo() {
        return this.activo;
    }
    
    public void setActivo(String activo) {
        this.activo = activo;
    }

    public Set<UsuarioRol> getUsuarioRols() {
        return this.usuarioRols;
    }
    
    public void setUsuarioRols(Set<UsuarioRol> usuarioRols) {
        this.usuarioRols = usuarioRols;
    }




}


