package co.edu.usb.clusterbp;
// Generated 17/01/2017 09:07:37 PM by Hibernate Tools 4.3.1.Final


import java.util.Date;

/**
 * VersionRep generated by hbm2java
 */
public class VersionRep  implements java.io.Serializable {


     private Long versionRepCodigo;
     private Repositorio repositorio;
     private String nombre;
     private String descripcionCambio;
     private Long usuCreador;
     private Date fechaCreacion;
     private Long usuModificador;
     private Date fechaModificacion;

    public VersionRep() {
    }

	
    public VersionRep(Long versionRepCodigo, Repositorio repositorio, Long usuCreador, Date fechaCreacion) {
        this.versionRepCodigo = versionRepCodigo;
        this.repositorio = repositorio;
        this.usuCreador = usuCreador;
        this.fechaCreacion = fechaCreacion;
    }
    public VersionRep(Long versionRepCodigo, Repositorio repositorio, String nombre, String descripcionCambio, Long usuCreador, Date fechaCreacion, Long usuModificador, Date fechaModificacion) {
       this.versionRepCodigo = versionRepCodigo;
       this.repositorio = repositorio;
       this.nombre = nombre;
       this.descripcionCambio = descripcionCambio;
       this.usuCreador = usuCreador;
       this.fechaCreacion = fechaCreacion;
       this.usuModificador = usuModificador;
       this.fechaModificacion = fechaModificacion;
    }
   
    public Long getVersionRepCodigo() {
        return this.versionRepCodigo;
    }
    
    public void setVersionRepCodigo(Long versionRepCodigo) {
        this.versionRepCodigo = versionRepCodigo;
    }
    public Repositorio getRepositorio() {
        return this.repositorio;
    }
    
    public void setRepositorio(Repositorio repositorio) {
        this.repositorio = repositorio;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcionCambio() {
        return this.descripcionCambio;
    }
    
    public void setDescripcionCambio(String descripcionCambio) {
        this.descripcionCambio = descripcionCambio;
    }
    public Long getUsuCreador() {
        return this.usuCreador;
    }
    
    public void setUsuCreador(Long usuCreador) {
        this.usuCreador = usuCreador;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Long getUsuModificador() {
        return this.usuModificador;
    }
    
    public void setUsuModificador(Long usuModificador) {
        this.usuModificador = usuModificador;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }




}


